### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Aloso** [nushell/blog#14]
Code blocks use the
````markdown
```
❯ ...
```
````

syntax. However, we can add `shell` to support syntax highlighting, like this:

````markdown
```shell
❯ ...
```
````

This highlights

- strings in single/double quotes
- flags and options starting with `-` or `--`
- table headers (lines starting with `#`)
- keywords, e.g. `if then elif else for while do ${...}`
- brackets/parentheses: `()[]{}` and some operators and words, e.g. `= ! && || == < > >= <= != $ true false echo set`.

We probably don't want to highlight keywords (because they don't exist in nu), so they can be easily disabled with CSS.

This also applies to http://www.nushell.sh. Here, some pages already use syntax highlighting but not all.

Additionally, I think that the `>` character should be replaced with `❯` in the 0.6.0 post and on http://www.nushell.sh. On the website, sometimes the path is shown as well, e.g.

````markdown
```
/home/jonathan/Source/nushell(master)> ls | where type == "Directory" | autoview
...
````

I think we can remove it, so the result is

````markdown
```shell
❯ ls | where type == "Directory" | autoview
...
````

**Comment by jonathandturner** [comment]
I've updated the last few blog posts to use it. Definitely a big improvement.

There are a couple places where the color isn't quite right (like `[table 3 rows]` in a shell example). Not sure if we can fix those, but yeah, definitely an overall improvement

**Comment by jonathandturner** [comment]
Forgot to close this as fixed
