### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by Aloso** [nushell/blog#15]
I believe you are hosting the website with GitHub Pages. [This article](https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https) explains how to automatically upgrade HTTP connections to HTTPS.

Also update links like this:
```html
<a href="http://blog.nushell.sh">
```

![nushell not secure](https://user-images.githubusercontent.com/15658558/69892977-a7dbf680-130b-11ea-8c76-9da330c429f0.png)

![nushell secure](https://user-images.githubusercontent.com/15658558/69892978-aa3e5080-130b-11ea-8217-61da6f37c783.png)

**Comment by jonathandturner** [comment]
I've updated the setting for github pages on the blog and main site

**Comment by jonathandturner** [comment]
@Aloso - I looked briefly for links on the blog. The ones I looked at seemed to all be https already

**Comment by jonathandturner** [comment]
I'm going to go ahead and close this. If you find other areas, we can open another issue for them.

**Comment by Aloso** [comment]
@jonathandturner The link I saw is on https://www.nushell.sh/, so it's in the other repository.

But since HTTP is automatically upgraded to HTTPS now, this is low priority now I guess :)
