### ISSUE TITLE
RSS/Atom

### ISSUE THREAD

**Issue by ThinkChaos** [nushell/blog#17]
It would be nice to have Jekyll generate an RSS feed for the blog entries.

I personally would subscribe to follow development of Nushell.

**Comment by jonathandturner** [comment]
There's an atom feed here: https://www.nushell.sh/blog/feed.xml - is that what you had in mind?

**Comment by ThinkChaos** [comment]
Yep that's it! Somehow I didn't see it on the page.
It would be nice to add `type="application/rss+xml"` to the `<a>` element on the blog so that it can be detected automatically 😃

**Comment by ongardie** [comment]
Ah, I just submitted PR #25 for this.

**Comment by Delapouite** [comment]
@ThinkChaos as the PR proposed by ongardie has been merged, do you think this issue can be closed? Thanks

**Comment by ThinkChaos** [comment]
Yep!
