### ISSUE TITLE
Colors need better contrast for accessibility

### ISSUE THREAD

**Issue by jonathandturner** [nushell/blog#7]
We should do a pass over the site with something like https://chrome.google.com/webstore/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf?hl=en and update the colors to have better contrast. I did a quick one and noticed a few aren't quite high enough for clear readability.

**Comment by sebastian-xyz** [comment]
On whet level of readability do you want to get?
Triple A seems pretty ambitious. I didn't find many colors that would pass the check for triple A on small size characters

**Comment by jonathandturner** [comment]
Oh I should have read this first, oops :)

I commented on the PR. Yeah, I think we should at least go for AA for the blog posts and the main part of the blog site. We can see if that's good enough for people, or if we need to go to AAA.

**Comment by sebastian-xyz** [comment]
On which page did you take the second screenshot in the PR? I've checked and didn't find a page that had this rating on the updated version

**Comment by jonathandturner** [comment]
@sebastian-xyz I think that was on the main blog page before you click on one of the blog posts

**Comment by sebastian-xyz** [comment]
@jonathandturner I checked but everything seems okay.

These are the values I get for the main blog page:
![AA_Blog_startpage](https://user-images.githubusercontent.com/52786998/69427144-31e5f700-0d2f-11ea-89f9-961b700c4fa3.png)

![AAA_Blog_startpage](https://user-images.githubusercontent.com/52786998/69427191-517d1f80-0d2f-11ea-9c98-de4ef98f1f25.png)

We are nearly having AAA. The only things that don't fit are 

* footer & link in footer (does it matter? I mean it is just a footnote)
* RSS-Button (could be achieved by making it slightly bigger)
* 'Visit our Website' Button (difficult to get a good contrast and having it in a different color than the background)

In the blog posts the things not reaching AAA are the links and of course the button at the top

**Comment by jonathandturner** [comment]
Oh good. I checked this morning and AA is green for me too, it must have just been checking the cached copy.

**Comment by jonathandturner** [comment]
I'm going to ahead and close this for now and then see if we need to get to AAA once people start using it.
